stages:
  - test
  - deploy

image: node:14.17.0

before_script:
- npm install

test:
  stage: test
  script:
  - npm run test

deploy:
  stage: deploy
  script:
    - docker build -t registry.gitlab.com/d2985/marvel-server-node .
    - docker push registry.gitlab.com/d2985/marvel-server-node