stages:
  - test
  - build
  - deploy

image: node:14.17.0

before_script:
- npm install

test:
  stage: test
  script:
  - npm run test

build:
  stage: build
  image: gitlab/dind
  services:
  - docker:dind
  script:
    - docker build -t registry.gitlab.com/d2985/marvel-server-node .

deploy:
  stage: deploy
  image: gitlab/dind
  services:
  - docker:dind
  script:
    - docker push registry.gitlab.com/d2985/marvel-server-node
